CREATE TABLE Sensor(
id int GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
name varchar(100) NOT NULL
);

CREATE TABLE Measurement(
id int GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
value int,
raining boolean,
sensor_id int REFERENCES Sensor(id) ON DELETE SET NULL
);

alter table measurement add column measurement_time timestamp;